"""edit company table

Revision ID: 0bea5e753198
Revises: 1d0eed0d5b70
Create Date: 2026-06-18 22:40:09.669732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0bea5e753198'
down_revision: Union[str, None] = '1d0eed0d5b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_payment_accounts_id'), 'payment_accounts', ['id'], unique=False)
    op.add_column('drivers', sa.Column('is_online', sa.Boolean(), nullable=False))
    op.add_column('drivers', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('drivers', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('current_lng', sa.Float(), nullable=True))
    op.create_index(op.f('ix_drivers_is_available'), 'drivers', ['is_available'], unique=False)
    op.create_index(op.f('ix_drivers_is_online'), 'drivers', ['is_online'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drivers_is_online'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_is_available'), table_name='drivers')
    op.drop_column('drivers', 'current_lng')
    op.drop_column('drivers', 'current_lat')
    op.drop_column('drivers', 'is_available')
    op.drop_column('drivers', 'is_online')
    op.drop_index(op.f('ix_payment_accounts_id'), table_name='payment_accounts')
    op.drop_table('payment_accounts')
    # ### end Alembic commands ###