"""create standalone courier driver table

Revision ID: 3189fb9be905
Revises: 52548857d84d
Create Date: 2026-08-19 23:00:01.638330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3189fb9be905'
down_revision: Union[str, None] = '52548857d84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Wipe old incompatible rows so NOT NULL columns won't fail
    op.execute("TRUNCATE TABLE courier_drivers CASCADE;")

    # 2. Add your new independent columns
    op.add_column('courier_drivers', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('courier_drivers', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('courier_drivers', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('courier_drivers', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('courier_drivers', sa.Column('is_email_verified', sa.Boolean(), nullable=False))
    op.add_column('courier_drivers', sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('courier_drivers', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('courier_drivers', sa.Column('is_admin_verified', sa.Boolean(), nullable=False))
    
    # 3. Handle indexes and drop old foreign keys/columns
    op.drop_index(op.f('ix_courier_drivers_user_id'), table_name='courier_drivers')
    op.create_index(op.f('ix_courier_drivers_email'), 'courier_drivers', ['email'], unique=True)
    op.create_index(op.f('ix_courier_drivers_phone_number'), 'courier_drivers', ['phone_number'], unique=True)
    op.drop_constraint(op.f('courier_drivers_user_id_fkey'), 'courier_drivers', type_='foreignkey')
    op.drop_column('courier_drivers', 'is_verified')
    op.drop_column('courier_drivers', 'user_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_drivers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('courier_drivers', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('courier_drivers_user_id_fkey'), 'courier_drivers', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_courier_drivers_phone_number'), table_name='courier_drivers')
    op.drop_index(op.f('ix_courier_drivers_email'), table_name='courier_drivers')
    op.create_index(op.f('ix_courier_drivers_user_id'), 'courier_drivers', ['user_id'], unique=True)
    op.drop_column('courier_drivers', 'is_admin_verified')
    op.drop_column('courier_drivers', 'verification_token_expires_at')
    op.drop_column('courier_drivers', 'verification_token')
    op.drop_column('courier_drivers', 'is_email_verified')
    op.drop_column('courier_drivers', 'hashed_password')
    op.drop_column('courier_drivers', 'phone_number')
    op.drop_column('courier_drivers', 'email')
    op.drop_column('courier_drivers', 'full_name')
    # ### end Alembic commands ###