"""add arrival confirmation fields

Revision ID: 376142a43e90
Revises: e2db6697f773
Create Date: 2026-09-28 22:59:22.525936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '376142a43e90'
down_revision: Union[str, None] = 'e2db6697f773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('arrival_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('trips', sa.Column('arrival_auto_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'arrival_auto_confirmed')
    op.drop_column('trips', 'arrival_confirmed')
    # ### end Alembic commands ###