"""add payment status

Revision ID: 3b29b6e19a43
Revises: 35d3449ad226
Create Date: 2026-08-26 16:56:44.361531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b29b6e19a43'
down_revision: Union[str, None] = '35d3449ad226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('courier_trips', sa.Column('payment_method', sa.String(), server_default='CASH', nullable=False))
    op.add_column('courier_trips', sa.Column('payment_status', sa.String(), server_default='PENDING', nullable=False))
    
    # paystack_reference is already nullable=True, so leave it exactly as it is
    op.add_column('courier_trips', sa.Column('paystack_reference', sa.String(), nullable=True))

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier_trips', 'payment_status')
    op.drop_column('courier_trips', 'paystack_reference')
    op.drop_column('courier_trips', 'payment_method')
    # ### end Alembic commands ###