"""create strictly isolated courier tables

Revision ID: 52548857d84d
Revises: 54e63af52223
Create Date: 2026-08-19 22:30:05.738417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52548857d84d'
down_revision: Union[str, None] = '54e63af52223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('MOTORCYCLE', 'CARGO_VAN', 'SPRINTER', 'BOX_TRUCK', name='couriervehicletype'), nullable=False),
    sa.Column('capacity_tons', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_vehicles_driver_id'), 'courier_vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_courier_vehicles_id'), 'courier_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_courier_vehicles_license_plate'), 'courier_vehicles', ['license_plate'], unique=True)
    op.create_table('courier_drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('can_do_labor', sa.Boolean(), nullable=False),
    sa.Column('interstate_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_vehicle_id'], ['courier_vehicles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_drivers_id'), 'courier_drivers', ['id'], unique=False)
    op.create_index(op.f('ix_courier_drivers_user_id'), 'courier_drivers', ['user_id'], unique=True)
    op.create_table('courier_trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.Enum('PACKAGE', 'STORE_PICKUP', 'RELOCATION', 'FREIGHT', name='courierjobtype'), nullable=False),
    sa.Column('cargo_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requires_labor', sa.Boolean(), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('estimated_distance_km', sa.Float(), nullable=False),
    sa.Column('pickup_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('pickup_contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dropoff_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dropoff_lat', sa.Float(), nullable=False),
    sa.Column('dropoff_lng', sa.Float(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dropoff_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EN_ROUTE_TO_PICKUP', 'LOADING', 'IN_TRANSIT', 'UNLOADING', 'COMPLETED', 'CANCELLED', name='courierstatus'), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('driver_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_loading_at', sa.DateTime(), nullable=True),
    sa.Column('started_transit_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['courier_drivers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['courier_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_trips_driver_id'), 'courier_trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_courier_trips_id'), 'courier_trips', ['id'], unique=False)
    op.create_index(op.f('ix_courier_trips_is_interstate'), 'courier_trips', ['is_interstate'], unique=False)
    op.create_index(op.f('ix_courier_trips_user_id'), 'courier_trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courier_trips_user_id'), table_name='courier_trips')
    op.drop_index(op.f('ix_courier_trips_is_interstate'), table_name='courier_trips')
    op.drop_index(op.f('ix_courier_trips_id'), table_name='courier_trips')
    op.drop_index(op.f('ix_courier_trips_driver_id'), table_name='courier_trips')
    op.drop_table('courier_trips')
    op.drop_index(op.f('ix_courier_drivers_user_id'), table_name='courier_drivers')
    op.drop_index(op.f('ix_courier_drivers_id'), table_name='courier_drivers')
    op.drop_table('courier_drivers')
    op.drop_index(op.f('ix_courier_vehicles_license_plate'), table_name='courier_vehicles')
    op.drop_index(op.f('ix_courier_vehicles_id'), table_name='courier_vehicles')
    op.drop_index(op.f('ix_courier_vehicles_driver_id'), table_name='courier_vehicles')
    op.drop_table('courier_vehicles')
    # ### end Alembic commands ###