"""rename to is_verified

Revision ID: 6376de85cb73
Revises: 3189fb9be905
Create Date: 2026-08-20 15:24:41.069899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6376de85cb73'
down_revision: Union[str, None] = '3189fb9be905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_drivers', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('courier_drivers', 'is_admin_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_drivers', sa.Column('is_admin_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('courier_drivers', 'is_verified')
    # ### end Alembic commands ###