"""edit company table

Revision ID: 8177ad7feeb7
Revises: 7a85c59ab914
Create Date: 2026-06-18 22:53:51.598206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8177ad7feeb7'
down_revision: Union[str, None] = '7a85c59ab914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'admins', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.drop_column('admins', 'company_id')
    # ### end Alembic commands ###