"""driver bank details

Revision ID: 82a5fc8c66d1
Revises: 3b29b6e19a43
Create Date: 2026-09-03 00:22:45.846032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82a5fc8c66d1'
down_revision: Union[str, None] = '3b29b6e19a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_driver_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('entry_type', sa.Enum('COMMISSION_DEBT', 'PAYOUT', 'BONUS', name='courierledgerentrytype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['courier_drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['courier_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_driver_history_driver_id'), 'courier_driver_history', ['driver_id'], unique=False)
    op.add_column('courier_drivers', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('courier_drivers', sa.Column('bank_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('courier_drivers', sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('courier_drivers', sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier_drivers', 'account_name')
    op.drop_column('courier_drivers', 'account_number')
    op.drop_column('courier_drivers', 'bank_code')
    op.drop_column('courier_drivers', 'bank_name')
    op.drop_index(op.f('ix_courier_driver_history_driver_id'), table_name='courier_driver_history')
    op.drop_table('courier_driver_history')
    # ### end Alembic commands ###