"""add arrival fields to courier_trips

Revision ID: 8d87d53881e4
Revises: 376142a43e90
Create Date: 2026-09-30 20:16:52.222444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d87d53881e4'
down_revision: Union[str, None] = '376142a43e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_trips', sa.Column('arrived_at', sa.DateTime(), nullable=True))
    op.add_column('courier_trips', sa.Column('arrival_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('courier_trips', sa.Column('arrival_auto_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courier_trips', 'arrival_auto_confirmed')
    op.drop_column('courier_trips', 'arrival_confirmed')
    op.drop_column('courier_trips', 'arrived_at')
    # ### end Alembic commands ###