"""driver update

Revision ID: b4dcb78bdda7
Revises: eb25d42f02e6
Create Date: 2026-08-04 13:40:03.150194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4dcb78bdda7'
down_revision: Union[str, None] = 'eb25d42f02e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drivers_current_vehicle_id'), 'drivers', ['current_vehicle_id'], unique=False)
    op.drop_constraint(op.f('drivers_current_vehicle_id_fkey'), 'drivers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('drivers_current_vehicle_id_fkey'), 'drivers', 'vehicle', ['current_vehicle_id'], ['id'])
    op.drop_index(op.f('ix_drivers_current_vehicle_id'), table_name='drivers')
    # ### end Alembic commands ###