"""point vehicle to courier_drivers instead of users

Revision ID: c32fd3946492
Revises: 6376de85cb73
Create Date: 2026-08-21 00:03:12.296621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c32fd3946492'
down_revision: Union[str, None] = '6376de85cb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('courier_vehicles_driver_id_fkey'), 'courier_vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'courier_vehicles', 'courier_drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courier_vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('courier_vehicles_driver_id_fkey'), 'courier_vehicles', 'users', ['driver_id'], ['id'])
    # ### end Alembic commands ###