"""user pending debt

Revision ID: d2a4a26964a7
Revises: 82a5fc8c66d1
Create Date: 2026-09-04 16:31:39.857330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd2a4a26964a7'
down_revision: Union[str, None] = '82a5fc8c66d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier_trips', sa.Column('applied_debt', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('pending_cancellation_fee', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_cancellation_fee')
    op.drop_column('courier_trips', 'applied_debt')
    # ### end Alembic commands ###