"""edit trip table

Revision ID: d2b50d9fc734
Revises: ba45b1d6dc52
Create Date: 2026-07-02 15:12:35.247478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2b50d9fc734'
down_revision: Union[str, None] = 'ba45b1d6dc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Drop the old table and its indexes FIRST to free up the Enum
    op.drop_index(op.f('ix_vehicles_company_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')

    # 2. Obliterate the old Enum from PostgreSQL entirely
    op.execute("DROP TYPE IF EXISTS towtrucktype CASCADE")

    # 3. NOW let Alembic create the new table and its fresh Enum without conflicts
    op.create_table('vehicle',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('company_id', sa.Uuid(), nullable=False),
        sa.Column('driver_id', sa.Uuid(), nullable=True),
        sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        
        # Back to the standard Enum declaration!
        sa.Column('vehicle_type', sa.Enum('FLATBED', 'WHEEL_LIFT', 'HEAVY_DUTY', name='towtrucktype'), nullable=False),
        
        sa.Column('capacity_tons', sa.Float(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_company_id'), 'vehicle', ['company_id'], unique=False)
    op.create_index(op.f('ix_vehicle_driver_id'), 'vehicle', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_license_plate'), 'vehicle', ['license_plate'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('make', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vehicle_type', postgresql.ENUM('FLATBED', 'WHEEL_LIFT', 'HEAVY_DUTY', name='towtrucktype'), autoincrement=False, nullable=False),
    sa.Column('capacity_tons', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('vehicles_company_id_fkey')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('vehicles_driver_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey'))
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicles_company_id'), 'vehicles', ['company_id'], unique=False)
    op.drop_index(op.f('ix_vehicle_license_plate'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_driver_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_company_id'), table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###