"""update trip model with cancelation_reason field

Revision ID: e2db6697f773
Revises: 7c03335e8692
Create Date: 2026-09-28 12:55:49.593235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2db6697f773'
down_revision: Union[str, None] = '7c03335e8692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'cancellation_reason')
    # ### end Alembic commands ###