"""driver update

Revision ID: eb25d42f02e6
Revises: d133bd90498c
Create Date: 2026-08-04 13:31:02.637421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb25d42f02e6'
down_revision: Union[str, None] = 'd133bd90498c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('current_vehicle_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'vehicle', ['current_vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'current_vehicle_id')
    # ### end Alembic commands ###